# Generated by Django 4.2.13 on 2024-07-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(
                choices=[
                    ("pidgeotpfp.jpg", "Pidgeot"),
                    ("pikachupfp.jpg", "Pikachu"),
                    ("charizardpfp.jpg", "Charizard"),
                    ("blastoisepfp.jpg", "Blastoise"),
                    ("venusaurpfp.jpg", "Venusaur"),
                    ("eeveepfp.jpg", "Eevee"),
                ],
                default="pidgeotpfp.jpg",
                max_length=100,
            ),
        ),
    ]
