# Generated by Django 4.2.13 on 2024-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_parent",
            field=models.BooleanField(default=False),
        ),
    ]
