# Generated by Django 4.2.13 on 2024-07-11 20:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_tcgcomment_mathcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mathcomment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="mathquestion",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="tcgcomment",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="tcgquestion",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
