# Generated by Django 4.2.13 on 2024-07-22 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "community",
            "0003_alter_mathcomment_content_alter_mathquestion_content_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mathcomment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tcgcomment",
            name="name",
        ),
        migrations.AddField(
            model_name="mathcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tcgcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
