# Generated by Django 4.2.13 on 2024-07-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
