# Generated by Django 4.2.13 on 2024-07-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practices_in_unit",
                to="learning.unit",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="practices",
            field=models.ManyToManyField(related_name="units", to="learning.practice"),
        ),
    ]
