# Generated by Django 4.2.13 on 2024-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_quiz_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
        migrations.AddField(
            model_name="completedquiz",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quiz",
            name="correct_answers",
            field=models.JSONField(default=dict),
        ),
    ]
