# Generated by Django 4.2.13 on 2024-07-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_practice_unit_alter_unit_practices"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="learning.unit",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="quiz",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_quiz",
                to="learning.quiz",
            ),
        ),
    ]
