# Generated by Django 4.2.13 on 2024-07-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0003_quiz_unit_alter_unit_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practice",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practices_in_unit",
                to="learning.unit",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="learning.unit",
            ),
        ),
    ]
