# Generated by Django 4.2.13 on 2024-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0004_alter_practice_unit_alter_quiz_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedquiz",
            name="perfect_score",
            field=models.BooleanField(default=False),
        ),
    ]
