# Generated by Django 4.2.13 on 2024-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0004_badge_alter_completedquiz_quiz_completedbadge"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completedquiz",
            options={"verbose_name_plural": "Completed Quizzes"},
        ),
        migrations.AddField(
            model_name="practice",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
