# Generated by Django 4.2.13 on 2024-07-16 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0005_alter_completedquiz_options_practice_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completedquiz",
            options={"verbose_name_plural": "Completed quizzes"},
        ),
    ]
