# Generated by Django 4.2.13 on 2024-07-27 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0005_completedquiz_perfect_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="grade_level",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="grade_level",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="grade_level",
        ),
    ]
