# Generated by Django 4.2.13 on 2024-07-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning",
            "0006_remove_practice_grade_level_remove_quiz_grade_level_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name="practice",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practices",
                to="learning.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="learning.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="learning.gradelevel",
            ),
        ),
    ]
