# Generated by Django 4.2.13 on 2024-07-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0008_registeredstudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="grade_level",
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name="registeredstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
