# Generated by Django 4.2.13 on 2024-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0008_completedunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradelevel",
            name="unit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
