# Generated by Django 4.2.13 on 2024-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0009_practice_grade_level_alter_registeredstudent_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="grade_level",
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name="practice",
            name="grade_level",
            field=models.CharField(default=0, max_length=3),
        ),
    ]
