# Generated by Django 4.2.13 on 2024-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0012_alter_child_parent_alter_child_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name_plural": "Children"},
        ),
        migrations.AlterModelOptions(
            name="registeredchild",
            options={"verbose_name_plural": "Registered children"},
        ),
        migrations.AddField(
            model_name="badge",
            name="icon",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
