# Generated by Django 4.2.13 on 2024-07-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0013_alter_child_options_alter_registeredchild_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
