# Generated by Django 4.2.13 on 2024-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0014_alter_badge_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grade_level", models.CharField(default="", max_length=3)),
                ("slug", models.SlugField(default="", unique=True)),
            ],
        ),
    ]
