# Generated by Django 4.2.13 on 2024-07-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0015_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="practices",
            field=models.ManyToManyField(to="learning.practice"),
        ),
        migrations.AddField(
            model_name="unit",
            name="quiz",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.quiz",
            ),
        ),
    ]
